services:
  app:
    build:
      ports:
      - "4200:4200"
      depends_on:
      - db
      volumes:
      - /back/src/data:/src/data
  
  db:
    image: mysql:8.0
    enviroment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: desafio
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      ports:
      - "3600:3600"
      volumes:
      - /back/src/data:/src/data
